### ISSUE TITLE
Goal 1: TAZ - Website

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/taz-apps#1]
**Description**:

The main TAZ website will be an entry point to explain what it is all about and guide users in creating a Semaphore identity to join the TAZ group. To do this, people will receive a card with a QR code containing an invitation code, which they will have to scan with their devices. Invitation codes can only be used once.

Once the identity is created and saved, users will be able to try different experiences or Semaphore applications.

**Tasks**:

- [x] #10
- [x] #2
- [x] #3
- [x] #8
- [x] #9
- [x] #11
- [x] #12
- [x] #13

**Comment by danilowhk** [comment]
Generate Qr Code done
