### ISSUE TITLE
Duplicate messageId

### ISSUE THREAD

**Issue by vimwitch** [semaphore-protocol/taz-apps#18]
The `addMessage` and `replyToMessage` functions in the `TazMessage.sol` contract use the counter differently.

`addMessage` uses the current value, then increments it. `replyToMessage` increments it, then uses the value.

If `replyToMessage` is called and then `addMessage` is called the same id will be emitted twice.

This is probably a bug in `replyToMessage`, [this](https://github.com/semaphore-protocol/taz-apps/blob/main/apps/contracts/contracts/TazMessage.sol#L113) variable is unused.

**Comment by vimwitch** [comment]
Actually it's definitely a bug. The [return value](https://github.com/semaphore-protocol/taz-apps/blob/main/apps/contracts/contracts/TazMessage.sol#L126) in `replyToMessage` mismatches the emitted value.

**Comment by danilowhk** [comment]
Ok! will work on this
